
(()=>{'use strict';
const S={registry:[],details:{},filtered:[],role:'ALL',q:'',shown:24,selected:null};
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function load(){const [r,d]=await Promise.all([fetch('./registry.json',{cache:'no-store'}).then(x=>x.json()),fetch('./player-details.json',{cache:'no-store'}).then(x=>x.json())]);S.registry=r.players;S.details=d.details;buildEngineBridge();bind();filter();syncState();document.body.dataset.ready='1';window.dispatchEvent(new CustomEvent('fs:ready'));}
function buildEngineBridge(){const host=$('#engine-bridge');const f=document.createDocumentFragment();for(const p of S.registry){const d=S.details[p.id]||{}, pu=d.purchase||{};const box=document.createElement('div');box.className='purchase-box';box.hidden=true;box.dataset.playerId=p.id;box.dataset.name=p.name;box.dataset.team=p.team;box.dataset.role=p.role;box.dataset.score=String(p.score||0);box.dataset.ideal=String(p.ideal||0);box.dataset.baseMax=String(p.max||0);box.innerHTML='<div class="live-decision"></div><input class="purchase-price" type="number"><input class="manager-name" type="text"><select class="owner-select">'+['','R1','R2','R3','R4','R5','R6','R7','R8','R9'].map(x=>`<option value="${x}">${x||'—'}</option>`).join('')+'</select><button class="purchase-btn win-btn" data-result="WON"></button><button class="purchase-btn lost-btn" data-result="LOST"></button>';f.appendChild(box)}host.appendChild(f)}
function bind(){$('#q').addEventListener('input',e=>{S.q=e.target.value.trim().toLowerCase();S.shown=24;filter()});$('#clear').onclick=()=>{$('#q').value='';S.q='';filter()};document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-role]').forEach(x=>x.classList.remove('on'));b.classList.add('on');S.role=b.dataset.role;S.shown=24;filter()});$('#more').onclick=()=>{S.shown+=24;render()};$('#list').addEventListener('click',e=>{const row=e.target.closest('.row');if(row)open(row.dataset.id)});$('#shade').onclick=close;$('#close').onclick=close;$('#sheet').addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(b)transact(b.dataset.act)});$('#nav-search').onclick=()=>{$('#q').focus();window.scrollTo({top:$('.toolbar').offsetTop-6,behavior:'smooth'})};$('#nav-list').onclick=()=>{close();window.scrollTo({top:$('.toolbar').offsetTop-6,behavior:'smooth'})};$('#nav-cockpit').onclick=()=>{const p=S.filtered[0]||S.registry[0];if(p)open(p.id)};window.addEventListener('storage',syncState)}
function filter(){let a=S.registry.filter(p=>S.role==='ALL'||p.role===S.role);if(S.q)a=a.filter(p=>(p.name+' '+p.team+' '+p.list_meta).toLowerCase().includes(S.q));a.sort((x,y)=>(y.score||0)-(x.score||0));S.filtered=a;render()}
function state(){try{return window.FS_AUCTION_ENGINE?.state?.()}catch(e){return null}}
function soldIds(){const st=state();return st?st.soldIds:new Set()}
function render(){const sold=soldIds();const a=S.filtered.filter(p=>!sold.has(p.id)).slice(0,S.shown);$('#count').textContent=`${S.filtered.length} trovati · ${a.length} renderizzati`;$('#list').innerHTML=a.map(p=>{let k=(p.decision||'').split(' ')[0].toUpperCase(); if(k==='ATTENDI')k='WAIT'; return `<article class="row" data-id="${esc(p.id)}"><span class="role ${esc(p.role)}">${esc(p.role)}</span><div class="name"><b>${esc(p.name)}</b><small>${esc(p.team)} · ${esc(p.list_meta.replace(p.team+' · ','')||p.role)}</small><span class="decision ${k}">${esc(p.decision)}</span></div><div class="nums"><b>${esc(p.score.toFixed? p.score.toFixed(1):p.score)}</b><small>MAX ${esc(p.max||0)}</small></div></article>`}).join('')||'<div class="empty">Nessun giocatore disponibile.</div>';$('#more').hidden=a.length>=S.filtered.filter(p=>!sold.has(p.id)).length;syncState()}
function syncState(){const st=state();if(!st)return;$('#budget').textContent=st.budget??500;$('#slots-total').textContent=st.slots??25;for(const r of ['P','D','C','A']){const need=st.managerStates?.ME?.needs?.[r];const cap={P:3,D:8,C:8,A:6}[r];$('#slot-'+r).textContent=`${cap-(need??cap)}/${cap}`}}
function open(id){const p=S.registry.find(x=>x.id===id),d=S.details[id];if(!p||!d)return;S.selected=p;$('#s-role').className='role '+p.role;$('#s-role').textContent=p.role;$('#s-name').textContent=p.name;$('#s-sub').textContent=d.subtitle||`${p.team} · ${p.role}`;$('#metrics').innerHTML=Object.entries(d.metrics||{}).map(([k,v])=>`<div class="metric"><small>${esc(k)}</small><b>${esc(v)}</b></div>`).join('');$('#instruction').innerHTML=`<b>Istruzione d’asta</b><p>${esc(d.instruction||p.decision)}</p>`;$('#blocks').innerHTML=(d.blocks||[]).map(x=>`<div class="block"><b>${esc(x.title)}</b><p>${esc(x.text)}</p></div>`).join('');$('#price').value='';$('#owner').value='';$('#runtime').textContent='Engine V4.0.23.1 LOCK · MAX base '+p.max;$('#sheet').classList.add('open');document.body.style.overflow='hidden';setTimeout(()=>$('#price').focus({preventScroll:true}),80)}
function close(){$('#sheet').classList.remove('open');document.body.style.overflow='';S.selected=null}
function transact(result){const p=S.selected;if(!p)return;const price=parseInt($('#price').value||'0',10);if(!price||price<1){$('#runtime').textContent='Inserisci il prezzo di aggiudicazione.';return}const bridge=[...document.querySelectorAll('#engine-bridge .purchase-box')].find(x=>x.dataset.playerId===p.id);if(!bridge)return;bridge.querySelector('.purchase-price').value=price;bridge.querySelector('.owner-select').value=result==='LOST'?$('#owner').value:'';bridge.querySelector('.manager-name').value='ME';if(result==='LOST'&&!$('#owner').value){$('#runtime').textContent='Se PERSO scegli il rivale.';return}bridge.querySelector(result==='WON'?'.win-btn':'.lost-btn').click();setTimeout(()=>{close();render();syncState()},20)}
load().catch(e=>{document.body.dataset.bootError='1';$('#count').textContent='BOOT ERROR';$('#list').innerHTML='<div class="empty">'+esc(e.message)+'</div>';window.dispatchEvent(new CustomEvent('fs:boot-error',{detail:{message:e.message}}));});
})();
