(()=>{'use strict';
async function sha(text){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function registryFingerprint(){const a=window.FS_APP?.registry?.()||[];return a.map(p=>[p.id,p.team,p.role,p.quote,p.fvm].join('|')).join('\n')}
async function payload(){const bundle=window.FS_STATE.exportBundle(),body={format:'FS_FANTASEGRETO_BACKUP_V3',schema:'FS_STATE_BUNDLE_V2',build:'V4.1.8.2 ENGINE PARITY + STATE HARDENING',engine:'V4.0.23.1 LINEAGE / V4.1.8.2 HARDENED PARITY + SHADOW GUARD',created_at:new Date().toISOString(),registry_count:(window.FS_APP?.registry?.()||[]).length,registry_hash:await sha(registryFingerprint()),bundle};body.payload_hash=await sha(JSON.stringify(body));return body}
async function download(){const x=await payload(),text=JSON.stringify(x,null,2),b=new Blob([text],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='FS_ASTA_V4182_'+new Date().toISOString().replace(/[:.]/g,'-')+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function validate(x){if(!x)throw Error('Backup vuoto');let clone={...x},h=x.payload_hash;delete clone.payload_hash;const actual=await sha(JSON.stringify(clone));if(h!==actual)throw Error('Checksum backup non valido');if(x.registry_count!==(window.FS_APP?.registry?.()||[]).length)throw Error('Registry count incompatibile');const rh=await sha(registryFingerprint());if(x.registry_hash!==rh)throw Error('Registry hash incompatibile');if(x.format==='FS_FANTASEGRETO_BACKUP_V3'&&x.schema==='FS_STATE_BUNDLE_V2'&&x.bundle){window.FS_STATE.validateSnapshot(x.bundle.state,{registry:window.FS_APP?.registry?.()});return{version:3,bundle:x.bundle}}if(x.format==='FS_FANTASEGRETO_BACKUP_V2'&&x.schema==='FS_STATE_V2'&&x.state){const bundle={schema:'FS_STATE_BUNDLE_V2',state:x.state,history:x.history||[],future:x.future||[],last_known_good:null};window.FS_STATE.validateSnapshot(bundle.state,{registry:window.FS_APP?.registry?.()});return{version:2,bundle}}throw Error('Formato backup non supportato')}
function restoreFile(file){const rd=new FileReader();rd.onload=async()=>{try{const x=JSON.parse(rd.result),v=await validate(x),before=window.FS_STATE.exportBundle();try{window.FS_STATE.importBundle(v.bundle,'BACKUP_RESTORE')}catch(e){window.FS_STATE.importBundle(before,'BACKUP_RESTORE_ROLLBACK');throw e}alert('Asta V4.1.8.2 ripristinata: stato + history + future verificati.')}catch(e){alert('Ripristino fallito: '+e.message)}};rd.readAsText(file)}
function bind(){document.getElementById('backup-save')?.addEventListener('click',download);document.getElementById('backup-file')?.addEventListener('change',e=>{if(e.target.files?.[0])restoreFile(e.target.files[0]);e.target.value=''})}
window.FS_BACKUP={payload,download,restoreFile,validate};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
