/* FantaSegreto V4.1.8.2 — ENGINE PARITY + STATE HARDENING.
   Formula lineage: V4.0.23.1 LOCK / V4.0.9 MOD+CS / V4.0.10 Shadow / V4.0.11 Pivot.
   DOM-free extraction. Shadow recursion fixed by capturing the pre-shadow max layer. */
(()=>{'use strict';
const START=500,LEAGUE_START=5000,TOTAL=25,LEAGUE_SLOTS=250,MIN_SLOT=1;
const CAPS={P:3,D:8,C:8,A:6},ROLE_BUDGET={P:38,D:92,C:145,A:225},OWNERS=['ME','R1','R2','R3','R4','R5','R6','R7','R8','R9'];
const registry=()=>window.FS_APP?.registry?.()||[];
const txLoad=()=>window.FS_STATE?.transactions?.()||[];
const txSave=x=>window.FS_STATE?.setTransactions?.(x)||[];
let premiumCache=null,premiumSig='';
function premiumSet(){const P=registry(),sig=P.length+':'+P.map(x=>x.id).join('|').length;if(premiumCache&&premiumSig===sig)return premiumCache;const set=new Set();for(const role of Object.keys(CAPS)){const a=P.filter(p=>p.role===role&&Number.isFinite(Number(p.score))).slice().sort((x,y)=>(Number(y.score)||0)-(Number(x.score)||0));a.slice(0,Math.max(1,Math.ceil(a.length*.10))).forEach(p=>set.add(p.id))}premiumCache=set;premiumSig=sig;return set}
function ownerName(owner,tx){if(owner==='ME')return'IO';const saved=window.FS_STATE?.managerNames?.()?.[owner];if(saved)return saved;const a=tx.filter(x=>x.owner===owner&&x.managerName);return a.length?a[a.length-1].managerName:owner}
function ownerState(owner,tx){const a=tx.filter(x=>x.owner===owner),spent=a.reduce((s,x)=>s+Number(x.price||0),0),roles={P:0,D:0,C:0,A:0},PREMIUM=premiumSet();a.forEach(x=>roles[x.role]=(roles[x.role]||0)+1);const needs={};for(const r in CAPS)needs[r]=Math.max(0,CAPS[r]-roles[r]);const slots=Math.max(0,TOTAL-a.length),budget=START-spent,minClose=slots*MIN_SLOT,safeAny=Math.max(0,budget-Math.max(0,(slots-1)*MIN_SLOT));const premiumCount=a.filter(x=>PREMIUM.has(x.id)).length;return{owner,name:ownerName(owner,tx),spent,budget,count:a.length,slots,roles,needs,minClose,safeAny,premiumCount}}
function state(){const P=registry(),tx=txLoad(),soldIds=new Set(tx.map(x=>x.id)),spentLeague=tx.reduce((s,x)=>s+Number(x.price||0),0),leagueBudget=LEAGUE_START-spentLeague,leagueSold=tx.length,leagueSlots=LEAGUE_SLOTS-leagueSold,leagueMinClose=leagueSlots*MIN_SLOT,leagueExtra=Math.max(0,leagueBudget-leagueMinClose),mine=tx.filter(x=>x.owner==='ME'),spent=mine.reduce((s,x)=>s+Number(x.price||0),0),budget=START-spent,slots=TOTAL-mine.length,minComplete=slots*MIN_SLOT,reserve=Math.min(Math.max(0,Math.round(budget*.07)),Math.max(0,budget-minComplete)),fire=Math.max(0,budget-minComplete-reserve),PREMIUM=premiumSet(),top=mine.filter(x=>PREMIUM.has(x.id)).length,topLeft=P.filter(p=>PREMIUM.has(p.id)&&!soldIds.has(p.id)).length,managerStates=Object.fromEntries(OWNERS.map(o=>[o,ownerState(o,tx)]));return{tx,soldIds,spentLeague,leagueBudget,leagueSold,leagueSlots,leagueMinClose,leagueExtra,mine,spent,budget,slots,minComplete,reserve,fire,top,topLeft,managerStates}}
function roleSupply(role,S){return registry().filter(p=>p.role===role&&!S.soldIds.has(p.id)).length}
function premiumRoleSupply(role,S){const PR=premiumSet();return registry().filter(p=>p.role===role&&PR.has(p.id)&&!S.soldIds.has(p.id)).length}
function behavior(owner,role,S){const a=S.tx.filter(x=>x.owner===owner),ra=a.filter(x=>x.role===role),P=registry();if(!a.length)return{sample:0,overpay:0,roleShare:0,factor:0};let over=0,n=0;for(const t of ra){const p=P.find(x=>x.id===t.id);if(p){over+=Number(t.price||0)-Number(p.ideal||0);n++}}const avg=n?over/n:0,roleShare=ra.length/a.length;return{sample:a.length,overpay:avg,roleShare,factor:Math.max(-.10,Math.min(.18,(avg/100)+(roleShare-.25)*.12))}}
function opponentPressure(p,S){const supply=Math.max(1,roleSupply(p.role,S)),premiumSupply=Math.max(1,premiumRoleSupply(p.role,S)),PR=premiumSet(),totalDemand=OWNERS.slice(1).reduce((z,o)=>z+S.managerStates[o].needs[p.role],0),scarcity=Math.min(1.6,totalDemand/supply),premiumScarcity=PR.has(p.id)?Math.min(1.7,totalDemand/premiumSupply):1;const details=OWNERS.slice(1).map(o=>{const m=S.managerStates[o],need=m.needs[p.role],bh=behavior(o,p.role,S);if(need<=0||m.slots<=0||m.budget<=0)return{owner:o,name:m.name,score:0,need,safe:0,budget:m.budget,status:'OUT',canContest:false,behavior:bh};const safe=Math.max(0,m.budget-Math.max(0,(m.slots-1)*MIN_SLOT)),cap=Math.min(1.25,safe/Math.max(1,Number(p.ideal)||1)),roleNeed=Math.min(1,need/Math.max(1,CAPS[p.role])),slotNeed=Math.min(1,m.slots/TOTAL),tierNeed=PR.has(p.id)?Math.max(.25,1-Math.min(1,m.premiumCount/3)):.45,ps=PR.has(p.id)?Math.min(1,premiumScarcity/1.25):Math.min(1,scarcity/1.25);let score=Math.round(100*(.38*Math.min(1,cap)+.24*roleNeed+.08*slotNeed+.14*tierNeed+.10*ps+.06*Math.max(0,Math.min(1,.5+bh.factor*3))));if(safe<(Number(p.ideal)||1))score=Math.round(score*.55);score=Math.max(0,Math.min(100,score));const canContest=safe>=Math.max(1,Math.round((Number(p.ideal)||1)*.75)),status=!canContest?'LOW':score>=75?'HIGH':score>=50?'MEDIUM':'LOW';return{owner:o,name:m.name,score,need,safe,budget:m.budget,status,canContest,roles:m.roles,behavior:bh}}).sort((a,b)=>b.score-a.score);const active=details.filter(x=>x.canContest),maxScore=details[0]?.score||0,avg=active.length?Math.round(active.reduce((s,x)=>s+x.score,0)/active.length):0,pressure=Math.min(100,Math.round(maxScore*.60+avg*.40));return{pressure,activeCount:active.length,details,scarcity,premiumScarcity,totalDemand,supply,premiumSupply}}
/* V4.1.8.1 core max — preserved as the base layer used by V4.0.23.1 v4Max. */
function coreLiveMax(p,S=state()){if(!p||S.soldIds.has(p.id)||S.managerStates.ME.needs[p.role]<=0)return 0;const base=Number(p.max);if(!Number.isFinite(base)||base<=0)return 0;const PR=premiumSet();let adj=1,topNeed=Math.max(0,3-S.top),scarcityTop=S.topLeft<=topNeed+2;if(PR.has(p.id)&&topNeed>0&&scarcityTop&&S.fire>base)adj=1.12;else if(PR.has(p.id)&&S.top>=3)adj=.92;else if(S.budget<S.minComplete+S.reserve+base)adj=.90;const op=opponentPressure(p,S);if(adj>=1)adj*=1+Math.min(.08,op.pressure/1250);const safe=Math.max(1,S.budget-Math.max(0,(S.slots-1)*MIN_SLOT));return Math.max(1,Math.min(safe,Math.round(base*adj)))}
function remaining(role,S){return registry().filter(p=>p.role===role&&!S.soldIds.has(p.id)&&Number.isFinite(Number(p.score)))}
function roleSpent(role,S){return S.mine.filter(x=>x.role===role).reduce((a,x)=>a+Number(x.price||0),0)}
function roleTarget(role,S){const remainingRoleSlots=S.managerStates.ME.needs[role],remSlots=S.slots||1,dynamic=Math.round(S.budget*(remainingRoleSlots/Math.max(1,remSlots)));return Math.max(remainingRoleSlots,Math.round((ROLE_BUDGET[role]*.55)+(dynamic*.45)))}
function topTier(p,role,S){const arr=remaining(role,S).slice().sort((a,b)=>Number(b.score)-Number(a.score)),cut=Math.max(1,Math.ceil(arr.length*.10));return arr.slice(0,cut).some(x=>x.id===p.id)}
function roleScarcity(role,S){const demand=Object.values(S.managerStates).reduce((z,m)=>z+m.needs[role],0),supply=Math.max(1,remaining(role,S).length);return{ratio:demand/supply,demand,supply}}
function costOfPass(p,S){const alt=remaining(p.role,S).filter(x=>x.id!==p.id).sort((a,b)=>Number(b.score)-Number(a.score)).slice(0,5);if(!alt.length)return{score:100,label:'CRITICO',best:null};const best=alt[0],gap=Math.max(0,Number(p.score)-Number(best.score)),sc=roleScarcity(p.role,S),top=topTier(p,p.role,S)?20:0,v=Math.round(Math.min(100,gap*2.5+Math.min(45,sc.ratio*22)+top));return{score:v,label:v>=75?'ALTO':v>=50?'MEDIO':'BASSO',best}}
/* Extracted V4.0.23.1 optimizer layer. */
function optimizerMax(p,S){if(!p||S.managerStates.ME.needs[p.role]<=0||!Number.isFinite(Number(p.score))||!Number.isFinite(Number(p.ideal)))return 0;const old=coreLiveMax(p,S);if(old<=0)return 0;const op=opponentPressure(p,S),cop=costOfPass(p,S),sc=roleScarcity(p.role,S);let mult=1;const needTop=Math.max(0,3-S.top);if(topTier(p,p.role,S)&&needTop>0)mult+=Math.min(.12,.035*needTop+.025*Math.max(0,sc.ratio-1));if(S.top>=3&&topTier(p,p.role,S))mult-=.05;if(cop.score>=75)mult+=.05;else if(cop.score<35)mult-=.03;mult+=Math.min(.05,op.pressure/2000);const target=roleTarget(p.role,S),spent=roleSpent(p.role,S);if(spent>target)mult-=Math.min(.08,(spent-target)/Math.max(1,target)*.12);if(p.role==='D')mult+=Math.max(0,(Math.min(100,Math.max(0,(Number(p.score)-45)*1.4))-55)/1000);if(p.role==='P')mult+=Math.max(0,(Math.min(100,Math.max(0,(Number(p.score)-40)*1.45))-55)/1200);const safe=Math.max(1,S.budget-Math.max(0,S.slots-1));return Math.max(1,Math.min(safe,Math.round(old*mult)))}
function qOwned(S,role){return(S.mine||[]).filter(x=>x.role===role).map(x=>registry().find(z=>z.id===x.id)?.score||0).sort((a,b)=>b-a)}
function teamEnv(p){const arr=registry().filter(x=>x.team===p.team&&(x.role==='P'||x.role==='D')&&Number.isFinite(Number(x.score))).sort((a,b)=>Number(b.score)-Number(a.score));if(!arr.length)return 50;const top=arr.slice(0,Math.min(6,arr.length));return Math.max(25,Math.min(90,Math.round(top.reduce((z,x)=>z+Number(x.score),0)/top.length)))}
function modifierMarginal(p,S){if(p.role!=='D')return{score:0,delta:0,label:'N/A',fit:'N/A'};const owned=qOwned(S,'D'),fourth=owned.length>=4?owned[3]:0,quality=Math.max(0,Math.min(100,Math.round((Number(p.score)-42)*1.55))),marginal=Math.max(0,Number(p.score)-fourth),rosterNeed=Math.max(0,4-owned.length),score=Math.round(Math.min(100,quality*.62+Math.min(30,marginal*1.8)+rosterNeed*6));let delta=score>=80?4:score>=65?3:score>=50?2:score>=35?1:0;if(owned.length>=5&&fourth>=Number(p.score))delta=Math.max(0,delta-2);return{score,delta,label:(score>=70?'ALTO ':score>=45?'MEDIO ':'BASSO ')+score+'/100',fit:owned.length<4?'COSTRUZIONE':'MARGINALE'}}
function cleanSheetMarginal(p,S){if(p.role!=='P')return{score:0,delta:0,label:'N/A',fit:'N/A'};const env=teamEnv(p),owned=qOwned(S,'P'),starterNeed=Math.max(0,1-owned.length),quality=Math.max(0,Math.min(100,Math.round((Number(p.score)-38)*1.5))),score=Math.round(Math.min(100,quality*.55+env*.35+starterNeed*10));let delta=score>=80?4:score>=65?3:score>=50?2:score>=35?1:0;if(owned.length>=2)delta=Math.max(0,delta-2);return{score,delta,label:(score>=70?'ALTO ':score>=45?'MEDIO ':'BASSO ')+score+'/100',fit:owned.length===0?'TITOLARE':'BLOCCO'}}
function modCsMax(p,S){const v=optimizerMax(p,S);if(v<=0)return 0;const m=modifierMarginal(p,S),c=cleanSheetMarginal(p,S),safe=Math.max(1,S.budget-Math.max(0,S.slots-1));return Math.max(0,Math.min(safe,v+m.delta+c.delta))}
function bestReplacement(p,S){return remaining(p.role,S).filter(x=>x.id!==p.id).sort((a,b)=>(Number(b.score)/Math.max(1,Number(b.ideal)||1))-(Number(a.score)/Math.max(1,Number(a.ideal)||1)))[0]||null}
function rosterDelta(p,price,S){const r=bestReplacement(p,S),repl=r?Number(r.score):Math.max(35,Number(p.score)*.70),qualityGap=Number(p.score)-repl,costPenalty=Math.max(0,price-Number(p.ideal))*.65,fitBonus=modifierMarginal(p,S).delta*2.5+cleanSheetMarginal(p,S).delta*2.5,scarcity=opponentPressure(p,S).scarcity||1;return qualityGap*1.9+fitBonus+Math.max(0,scarcity-1)*5-costPenalty}
/* V4.0.10 lineage. The legacy source had a recursive self-call and the raw shadow search can explode far above the calibrated player/role layers.
   V4.1.8.2 therefore preserves the raw value for diagnostics, then applies a deterministic safety guard: shadow may add at most min(8 credits, 8% of MOD+CS max).
   This is a safety correction, not a calibration write: it prevents a broken legacy layer from overriding the locked upstream semantics. */
function shadowRawMax(p,S){const safe=Math.max(1,S.budget-Math.max(0,S.slots-1));let lo=1,hi=safe,best=1;while(lo<=hi){const m=Math.floor((lo+hi)/2);if(rosterDelta(p,m,S)>=0){best=m;lo=m+1}else hi=m-1}const live=modCsMax(p,S);return Math.max(1,Math.min(safe,Math.max(live,best)))}
function shadowDeltaCap(live){if(live<=0)return 0;return Math.max(1,Math.min(8,Math.ceil(live*.08)))}
function shadowMax(p,S){const live=modCsMax(p,S);if(live<=0)return 0;const raw=shadowRawMax(p,S),cap=shadowDeltaCap(live),safe=Math.max(1,S.budget-Math.max(0,S.slots-1));return Math.max(1,Math.min(safe,live+Math.min(Math.max(0,raw-live),cap)))}
function preNewsMax(p,S){const safe=Math.max(1,S.budget-Math.max(0,S.slots-1));return Math.max(0,Math.min(safe,shadowMax(p,S)))}
function applyNewsMax(p,raw,S){let v=raw;const n=p?._news;if(n&&Number.isFinite(Number(n.applied_max_pct))){const pct=Number(n.applied_max_pct);v=pct>=0?Math.ceil(v*(1+pct/100)):Math.floor(v*(1+pct/100))}if(p?._valuation?.hard_cap&&Number.isFinite(Number(p._valuation.bridge_max)))v=Math.min(v,Number(p._valuation.bridge_max));const safe=Math.max(1,S.budget-Math.max(0,S.slots-1));return Math.max(0,Math.min(safe,Math.round(v)))}
function liveMax(p,S=state()){if(!p||S.soldIds.has(p.id)||S.managerStates.ME.needs[p.role]<=0)return 0;if(!Number.isFinite(Number(p.max))||!Number.isFinite(Number(p.ideal))||!Number.isFinite(Number(p.score)))return 0;return applyNewsMax(p,preNewsMax(p,S),S)}
function exactMax(p,S=state()){const safe=Math.max(0,S.budget-Math.max(0,S.slots-1)),raw=Number(liveMax(p,S));if(!Number.isFinite(raw))return 0;return Math.max(0,Math.min(safe,raw))}
function decision(price,p,S=state()){const m=exactMax(p,S);if(m<=0)return'PASS';const x=Number(price);if(!Number.isFinite(x)||x<=0)return m>=Number(p.ideal||0)?'WAIT':'PASS';if(x<=Number(p.ideal||0))return'BUY';if(x<=m)return'WAIT';return'PASS'}
function instruction(p,S=state()){const m=exactMax(p,S),ideal=Number(p.ideal||0);if(m<=0)return p?._news?.action==='REGISTRY_WRITE_BUY'?'BUY segnalato dalle news, ma MAX FS non disponibile: attendi ricalcolo.':'PASS: MAX FS non disponibile o slot non acquistabile.';if(m<=ideal)return`BUY/WAIT fino a ${m} crediti · STOP oltre ${m}.`;return`BUY fino a ${ideal} crediti · WAIT ${ideal+1}–${m} · STOP oltre ${m}.`}
function utility(p,S){const lm=exactMax(p,S),op=opponentPressure(p,S),cop=costOfPass(p,S),sc=roleScarcity(p.role,S),value=Number(p.score)/Math.max(1,Number(p.ideal)||1),budgetFit=Math.max(-1,Math.min(1,(roleTarget(p.role,S)-roleSpent(p.role,S))/Math.max(1,roleTarget(p.role,S))));return value*26+Number(p.score)*.55+cop.score*.18+Math.min(20,sc.ratio*8)-op.pressure*.06+budgetFit*8+(topTier(p,p.role,S)&&S.top<3?12:0)+(lm>=Number(p.ideal||0)?4:-4)}
function candidates(S,role='AUTO'){let arr=registry().filter(p=>!S.soldIds.has(p.id)&&S.managerStates.ME.needs[p.role]>0&&Number.isFinite(Number(p.score))&&Number.isFinite(Number(p.ideal))&&Number.isFinite(Number(p.max)));if(role!=='AUTO')arr=arr.filter(p=>p.role===role);return arr.sort((a,b)=>utility(b,S)-utility(a,S))}
function pivotSurvival(p,S){const op=opponentPressure(p,S),supply=Math.max(1,op.supply||1),demand=Math.max(0,op.totalDemand||0),scarcity=Math.min(1,demand/supply),pressure=(op.pressure||0)/100,premium=Math.max(0,Math.min(1,(Number(p.score)-75)/20)),prob=Math.round(100*(1-(.48*scarcity+.32*pressure+.20*premium)));return Math.max(5,Math.min(95,prob))}
function pivots(p,S=state()){return candidates(S,p.role).filter(x=>x.id!==p.id).slice(0,4).map(x=>({...x,survival:pivotSurvival(x,S)})).sort((a,b)=>(b.survival+Number(b.score))-(a.survival+Number(a.score)))}
function parityLayers(p,S=state()){const m=modifierMarginal(p,S),c=cleanSheetMarginal(p,S),mc=modCsMax(p,S),sr=shadowRawMax(p,S),sg=shadowMax(p,S);return{core:coreLiveMax(p,S),optimizer:optimizerMax(p,S),modifier:m,clean_sheet:c,mod_cs:mc,shadow_raw:sr,shadow_guarded:sg,shadow_delta_cap:shadowDeltaCap(mc),pre_news:preNewsMax(p,S),news_pct:p?._news?.applied_max_pct??null,exact:exactMax(p,S),recursion_guard:'PRE_SHADOW_CAPTURED',shadow_guard:'MIN_8_CREDITS_OR_8_PERCENT_UPLIFT'}}
function validateTransaction({playerId,result,owner,price}){const P=registry(),p=P.find(x=>x.id===playerId),S=state();if(!p)return{ok:false,error:'Giocatore non presente nel registry'};price=Number(price);if(!Number.isInteger(price)||price<1)return{ok:false,error:'Prezzo non valido'};const target=result==='WON'?'ME':owner;if(result!=='WON'&&result!=='LOST')return{ok:false,error:'Esito non valido'};if(result==='LOST'&&!OWNERS.slice(1).includes(owner))return{ok:false,error:'Rivale non valido'};if(S.soldIds.has(p.id))return{ok:false,error:'Giocatore già assegnato'};const m=S.managerStates[target];if(!m)return{ok:false,error:'Manager non valido'};if(m.budget-price<0)return{ok:false,error:'Budget manager insufficiente'};if(m.count>=TOTAL)return{ok:false,error:'Manager già a 25 giocatori'};if(m.roles[p.role]>=CAPS[p.role])return{ok:false,error:'Slot '+p.role+' già completo'};if(m.budget-price<(m.slots-1)*MIN_SLOT)return{ok:false,error:'Acquisto rende impossibile completare la rosa'};if(result==='WON'){const mx=exactMax(p,S);if(mx<=0)return{ok:false,error:'MAX FS non disponibile: ricalcolo richiesto'};if(price>mx+1e-9)return{ok:false,error:'Prezzo '+price+' supera MAX ESATTO '+mx,max:mx}}return{ok:true,p,target,price,S}}
function transaction(input){const v=validateTransaction(input);if(!v.ok)return v;window.FS_STATE?.begin?.('TRANSACTION');try{const tx=txLoad(),now={id:v.p.id,name:v.p.name,team:v.p.team,role:v.p.role,price:v.price,owner:v.target,result:input.result,managerName:v.target==='ME'?'IO':(window.FS_STATE?.managerNames?.()?.[v.target]||v.target),ts:new Date().toISOString(),engine:'V4.0.23.1 LINEAGE / V4.1.8.2 HARDENED PARITY + SHADOW GUARD'};txSave([...tx,now]);const post=state(),checks=post.managerStates[v.target].budget>=0&&post.managerStates[v.target].count<=25&&post.managerStates[v.target].roles[v.p.role]<=CAPS[v.p.role];if(!checks)throw Error('Postcondition transazione fallita');const snap=window.FS_STATE?.commit?.('TRANSACTION');window.dispatchEvent(new CustomEvent('fs:state-changed',{detail:{type:input.result,transaction:now,state_hash:snap?.state_hash}}));return{ok:true,transaction:now,state:post}}catch(e){window.FS_STATE?.rollback?.();return{ok:false,error:e.message}}}
window.FS_AUCTION_ENGINE={version:'V4.0.23.1 LOCK / V4.1.8.2 PARITY+SHADOW_GUARD',state,coreLiveMax,liveMax,exactMax,decision,instruction,opponentPressure,costOfPass,modifierMarginal,cleanSheetMarginal,bestReplacement,rosterDelta,shadowRawMax,shadowMax,shadowDeltaCap,pivotSurvival,pivots,candidates,parityLayers,transaction,validateTransaction,roleCaps:CAPS,owners:OWNERS};
window.FS_V4={v4Max:liveMax,exactMax,pivots,pivotSurvival,modifierMarginal,cleanSheetMarginal,shadowRawMax,shadowMax,costOfPass};
})();
