const assert=require('node:assert/strict');
const fs=require('node:fs');
const sim=require('./premium-monte-carlo-v1.js');
const contract=JSON.parse(fs.readFileSync('FS_PREMIUM_MATCH_EVIDENCE_V1.json','utf8'));
assert.equal(contract.inputs.league_rules.substitution_count,5);
assert.equal(contract.inputs.league_rules.substitution_mode,'SAME_ROLE');
assert.equal(contract.inputs.league_rules.module_change_allowed,false);
assert.equal(contract.inputs.home_starting_xi.length,11);
assert.equal(contract.inputs.away_starting_xi.length,11);
assert.equal(contract.inputs.home_bench.length,12);
assert.equal(contract.inputs.away_bench.length,12);
const blocked=sim.simulate(contract,{},{iterations:100,seed:20261009});
assert.equal(blocked.status,'BLOCKED_PENDING_VERIFIED_INPUTS');
assert.equal(blocked.simulation_count,0);
assert.ok(blocked.errors.some(x=>x.includes('goal_thresholds')));
const invalid=structuredClone(contract);
invalid.inputs.league_rules.substitution_count=6;
assert.ok(sim.validate(invalid,{}).some(x=>x.includes('five substitutions')));
console.log('FS_PREMIUM_CONTRACT_SAFE_TEST_PASS');
