(()=>{'use strict';
const KEYS={
 STATE:'fantasegreto:state:v2',
 HISTORY:'fantasegreto:history:v2',
 FUTURE:'fantasegreto:future:v2',
 LKG:'fantasegreto:lkg:v2',
 MIGRATION:'fantasegreto:migration:v2'
};
const LEGACY={TX:'fs_gold_auction_v393',MN:'fs_v412_manager_names',H:'fs_v418_history',F:'fs_v418_future',LKG:'fs_v418_last_known_good'};
const MAX=60, OWNERS=new Set(['ME','R1','R2','R3','R4','R5','R6','R7','R8','R9']), ROLES=new Set(['P','D','C','A']);
const clone=x=>JSON.parse(JSON.stringify(x));
const readRaw=(k,d)=>{try{const v=localStorage.getItem(k);return v===null?clone(d):JSON.parse(v)}catch(e){return clone(d)}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function digestObj(o){const s=JSON.stringify(o);let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return ('00000000'+(h>>>0).toString(16)).slice(-8)}
function emptyState(){return{schema:'FS_STATE_V2',revision:0,updated_at:new Date().toISOString(),transactions:[],manager_names:{}}}
function normalizeState(s){const x=s&&typeof s==='object'?clone(s):emptyState();x.schema='FS_STATE_V2';x.revision=Number.isInteger(x.revision)?x.revision:0;x.updated_at=x.updated_at||new Date().toISOString();x.transactions=Array.isArray(x.transactions)?x.transactions:[];x.manager_names=x.manager_names&&typeof x.manager_names==='object'?x.manager_names:{};return x}
function stateHash(s){const x=normalizeState(s);return digestObj({transactions:x.transactions,manager_names:x.manager_names})}
function snapshot(reason='SNAPSHOT'){const x=normalizeState(readRaw(KEYS.STATE,emptyState()));return{...x,reason,ts:new Date().toISOString(),state_hash:stateHash(x)}}
function validateSnapshot(s,{registry}={}){if(!s||s.schema!=='FS_STATE_V2'||!Array.isArray(s.transactions))throw Error('Snapshot FS_STATE_V2 non valido');const ids=new Set(),reg=registry?new Set(registry.map(p=>p.id)):null;for(const t of s.transactions){if(!t||typeof t.id!=='string'||!t.id)throw Error('Transazione senza PlayerID');if(ids.has(t.id))throw Error('Doppia ownership nel backup: '+t.id);ids.add(t.id);if(reg&&!reg.has(t.id))throw Error('PlayerID non presente nel registry corrente: '+t.id);if(!OWNERS.has(t.owner))throw Error('Owner non valido: '+t.owner);if(!ROLES.has(t.role))throw Error('Ruolo non valido: '+t.role);if(!Number.isInteger(Number(t.price))||Number(t.price)<1)throw Error('Prezzo non valido per '+t.id)}return true}
function restoreSnapshot(s,reason='RESTORE',{emit=true,registry}={}){const x=normalizeState(s);validateSnapshot(x,{registry});x.revision=Math.max(0,Number.isInteger(x.revision)?x.revision:0);x.updated_at=new Date().toISOString();write(KEYS.STATE,x);const chk={...x,reason,ts:new Date().toISOString(),state_hash:stateHash(x)};write(KEYS.LKG,chk);if(emit)window.dispatchEvent(new CustomEvent('fs:state-changed',{detail:{type:reason,state_hash:chk.state_hash,revision:x.revision}}));return chk}
function migrateLegacy(){if(localStorage.getItem(KEYS.STATE)!==null)return readRaw(KEYS.STATE,emptyState());const tx=readRaw(LEGACY.TX,[]),mn=readRaw(LEGACY.MN,{}),legacyHistory=readRaw(LEGACY.H,[]),legacyFuture=readRaw(LEGACY.F,[]),legacyLkg=readRaw(LEGACY.LKG,null),reg=window.FS_APP?.registry?.();const x=normalizeState({schema:'FS_STATE_V2',revision:0,transactions:Array.isArray(tx)?tx:[],manager_names:mn||{}}),conv=a=>Array.isArray(a)?a.filter(z=>z&&Array.isArray(z.transactions)).map(z=>normalizeState(z)).slice(-MAX):[],h=conv(legacyHistory),f=conv(legacyFuture);try{validateSnapshot(x,{registry:reg});for(const z of h)validateSnapshot(z,{registry:reg});for(const z of f)validateSnapshot(z,{registry:reg});let lkg=null;if(legacyLkg&&Array.isArray(legacyLkg.transactions)){lkg=normalizeState(legacyLkg);validateSnapshot(lkg,{registry:reg})}write(KEYS.STATE,x);write(KEYS.HISTORY,h);write(KEYS.FUTURE,f);write(KEYS.LKG,lkg?{...lkg,reason:'LEGACY_LKG_MIGRATION',ts:new Date().toISOString(),state_hash:stateHash(lkg)}:{...x,reason:'LEGACY_MIGRATION',ts:new Date().toISOString(),state_hash:stateHash(x)});write(KEYS.MIGRATION,{status:'PASS',from:LEGACY,to:KEYS,at:new Date().toISOString(),transactions:x.transactions.length,history:h.length,future:f.length,legacy_keys_preserved:true});return x}catch(e){write(KEYS.MIGRATION,{status:'BLOCKED',from:LEGACY,to:KEYS,at:new Date().toISOString(),error:e.message,legacy_keys_preserved:true});throw Error('Migrazione stato legacy bloccata: '+e.message)}}
migrateLegacy();
let active=null;
function begin(reason='TRANSACTION'){if(active)return clone(active);active=snapshot('PRE_'+reason);return clone(active)}
function commit(reason='COMMIT'){if(!active)active=snapshot('PRE_IMPLICIT');const cur=normalizeState(readRaw(KEYS.STATE,emptyState()));const postHash=stateHash(cur);if(active.state_hash!==postHash){const h=readRaw(KEYS.HISTORY,[]);h.push(normalizeState(active));write(KEYS.HISTORY,h.slice(-MAX));write(KEYS.FUTURE,[]);cur.revision=(Number(cur.revision)||0)+1;cur.updated_at=new Date().toISOString();write(KEYS.STATE,cur)}const post={...cur,reason:'POST_'+reason,ts:new Date().toISOString(),state_hash:stateHash(cur)};write(KEYS.LKG,post);active=null;return clone(post)}
function rollback(){if(!active)return false;restoreSnapshot(active,'ROLLBACK',{emit:true,registry:window.FS_APP?.registry?.()});active=null;return true}
function undo(){const h=readRaw(KEYS.HISTORY,[]);if(!h.length)return false;const cur=normalizeState(readRaw(KEYS.STATE,emptyState())),prev=normalizeState(h.pop()),f=readRaw(KEYS.FUTURE,[]);f.push(cur);write(KEYS.HISTORY,h);write(KEYS.FUTURE,f.slice(-MAX));prev.revision=(cur.revision||0)+1;restoreSnapshot(prev,'UNDO',{registry:window.FS_APP?.registry?.()});active=null;return true}
function redo(){const f=readRaw(KEYS.FUTURE,[]);if(!f.length)return false;const cur=normalizeState(readRaw(KEYS.STATE,emptyState())),next=normalizeState(f.pop()),h=readRaw(KEYS.HISTORY,[]);h.push(cur);write(KEYS.HISTORY,h.slice(-MAX));write(KEYS.FUTURE,f);next.revision=(cur.revision||0)+1;restoreSnapshot(next,'REDO',{registry:window.FS_APP?.registry?.()});active=null;return true}
function transactions(){return clone(normalizeState(readRaw(KEYS.STATE,emptyState())).transactions)}
function setTransactions(tx,{emit=false,type='SET_TRANSACTIONS'}={}){if(!Array.isArray(tx))throw Error('transactions deve essere array');const s=normalizeState(readRaw(KEYS.STATE,emptyState()));s.transactions=clone(tx);validateSnapshot(s,{registry:window.FS_APP?.registry?.()});write(KEYS.STATE,s);if(emit)window.dispatchEvent(new CustomEvent('fs:state-changed',{detail:{type}}));return clone(s.transactions)}
function managerNames(){return clone(normalizeState(readRaw(KEYS.STATE,emptyState())).manager_names)}
function setManagerName(id,name){if(!/^R[1-9]$/.test(id))throw Error('Manager ID non valido');begin('MANAGER_NAME');const s=normalizeState(readRaw(KEYS.STATE,emptyState()));s.manager_names[id]=String(name||'').trim()||('Manager '+id.slice(1));write(KEYS.STATE,s);const out=commit('MANAGER_NAME');window.dispatchEvent(new CustomEvent('fs:state-changed',{detail:{type:'MANAGER_NAME',state_hash:out.state_hash}}));return s.manager_names[id]}
function lastKnownGood(){return readRaw(KEYS.LKG,null)}
function recoverLastKnownGood(){const x=lastKnownGood();if(!x)return false;restoreSnapshot(x,'LKG_RECOVERY',{registry:window.FS_APP?.registry?.()});return true}
function clearHistory(){write(KEYS.HISTORY,[]);write(KEYS.FUTURE,[]);active=null}
function exportBundle(){return{schema:'FS_STATE_BUNDLE_V2',state:normalizeState(readRaw(KEYS.STATE,emptyState())),history:readRaw(KEYS.HISTORY,[]).map(normalizeState),future:readRaw(KEYS.FUTURE,[]).map(normalizeState),last_known_good:readRaw(KEYS.LKG,null)}}
function importBundle(bundle,reason='BUNDLE_RESTORE'){if(!bundle||bundle.schema!=='FS_STATE_BUNDLE_V2')throw Error('Bundle FS_STATE_BUNDLE_V2 non valido');const reg=window.FS_APP?.registry?.();validateSnapshot(bundle.state,{registry:reg});for(const s of bundle.history||[])validateSnapshot(s,{registry:reg});for(const s of bundle.future||[])validateSnapshot(s,{registry:reg});const before={state:localStorage.getItem(KEYS.STATE),history:localStorage.getItem(KEYS.HISTORY),future:localStorage.getItem(KEYS.FUTURE),lkg:localStorage.getItem(KEYS.LKG)};try{const st=normalizeState(bundle.state);st.revision=(normalizeState(readRaw(KEYS.STATE,emptyState())).revision||0)+1;st.updated_at=new Date().toISOString();write(KEYS.STATE,st);write(KEYS.HISTORY,(bundle.history||[]).map(normalizeState).slice(-MAX));write(KEYS.FUTURE,(bundle.future||[]).map(normalizeState).slice(-MAX));const lkg={...st,reason,ts:new Date().toISOString(),state_hash:stateHash(st)};write(KEYS.LKG,lkg);active=null;window.dispatchEvent(new CustomEvent('fs:state-changed',{detail:{type:reason,state_hash:lkg.state_hash,revision:st.revision}}));return clone(exportBundle())}catch(e){for(const [k,v] of Object.entries({[KEYS.STATE]:before.state,[KEYS.HISTORY]:before.history,[KEYS.FUTURE]:before.future,[KEYS.LKG]:before.lkg}))v===null?localStorage.removeItem(k):localStorage.setItem(k,v);throw e}}
window.FS_STATE={begin,commit,rollback,undo,redo,snapshot,restore:restoreSnapshot,lastKnownGood,recoverLastKnownGood,clearHistory,digestObj,stateHash,validateSnapshot,transactions,setTransactions,managerNames,setManagerName,exportBundle,importBundle,keys:KEYS,legacyKeys:LEGACY};
})();
